package dev.chililisoup.creativecraftingmenus.config;

import dev.chililisoup.creativecraftingmenus.config.BannerPresets.PresetGroupItem.SerializedPresetGroupItem;

import static net.minecraft.world.item.DyeColor.*;
import static net.minecraft.world.level.block.entity.BannerPatterns.*;

public abstract class DefaultBannerPresets {
    public static final SerializedPresetGroupItem ALPHABET =
            new SerializedPresetGroupItem.GroupBuilder()
                    .banner(WHITE, builder -> builder // A
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(WHITE, BORDER)
                    )
                    // TODO: Make alternate default B that's survival friendly
                    .banner(WHITE, builder -> builder // B
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // C
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // D
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(BLACK, HALF_VERTICAL)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // E
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // F
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // G
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, HALF_HORIZONTAL)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // H
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // I
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // J
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, HALF_HORIZONTAL)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // K
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, DIAGONAL_LEFT)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // L
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // M
                            .layer(BLACK, TRIANGLE_TOP)
                            .layer(WHITE, TRIANGLES_TOP)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // N
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // O
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // P
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, HALF_HORIZONTAL_MIRROR)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(BLACK, builder -> builder // Q
                            .layer(WHITE, RHOMBUS_MIDDLE)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, SQUARE_BOTTOM_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // R
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, HALF_HORIZONTAL_MIRROR)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // S
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, RHOMBUS_MIDDLE)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // T
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // U
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // V
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(WHITE, TRIANGLE_BOTTOM)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // W
                            .layer(BLACK, TRIANGLE_BOTTOM)
                            .layer(WHITE, TRIANGLES_BOTTOM)
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // X
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // Y
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, HALF_VERTICAL_MIRROR)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // Z
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, BORDER)
                    )
                    .build();

    public static final SerializedPresetGroupItem SYMBOLS =
            new SerializedPresetGroupItem.GroupBuilder()
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(WHITE, HALF_HORIZONTAL_MIRROR)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(BLACK, SQUARE_BOTTOM_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(BLACK, TRIANGLES_BOTTOM)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(BLACK, HALF_HORIZONTAL)
                            .layer(WHITE, STRIPE_CENTER)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, TRIANGLES_BOTTOM)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, HALF_VERTICAL)
                            .layer(WHITE, STRIPE_MIDDLE)
                            .layer(WHITE, BORDER)
                            .layer(WHITE, STRIPE_TOP)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(WHITE, STRIPE_CENTER)
                    )
                    .banner(BLACK, builder -> builder //
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, STRIPE_CENTER)
                            .layer(BLACK, TRIANGLES_TOP)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(BLACK, MOJANG)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, RHOMBUS_MIDDLE)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(WHITE, BORDER)
                            .layer(WHITE, STRIPE_CENTER)
                            .layer(BLACK, STRIPE_CENTER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, BORDER)
                            .layer(WHITE, CROSS)
                            .layer(WHITE, DIAGONAL_LEFT)
                            .layer(WHITE, DIAGONAL_RIGHT_MIRROR)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, STRIPE_SMALL)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_SMALL)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, BORDER)
                            .layer(WHITE, STRAIGHT_CROSS)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_RIGHT)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(WHITE, STRIPE_TOP)
                            .layer(WHITE, STRIPE_BOTTOM)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_LEFT)
                            .layer(BLACK, STRIPE_MIDDLE)
                            .layer(WHITE, CURLY_BORDER)
                            .layer(WHITE, STRIPE_TOP)
                            .layer(WHITE, STRIPE_BOTTOM)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, RHOMBUS_MIDDLE)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_BOTTOM)
                            .layer(WHITE, RHOMBUS_MIDDLE)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, STRIPE_TOP)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_TOP)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(WHITE, CURLY_BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, SQUARE_TOP_RIGHT)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(BLACK, SQUARE_BOTTOM_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, SQUARE_TOP_LEFT)
                            .layer(BLACK, SQUARE_BOTTOM_LEFT)
                            .layer(BLACK, STRIPE_CENTER)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, HALF_VERTICAL)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, HALF_VERTICAL_MIRROR)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNRIGHT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder //
                            .layer(BLACK, STRIPE_DOWNLEFT)
                            .layer(BLACK, STRIPE_TOP)
                            .layer(WHITE, STRIPE_BOTTOM)
                            .layer(WHITE, STRIPE_RIGHT)
                            .layer(WHITE, STRIPE_LEFT)
                            .layer(WHITE, BORDER)
                    )
                    .build();

    public static final SerializedPresetGroupItem MATH =
            new SerializedPresetGroupItem.GroupBuilder()
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, CURLY_BORDER)
                        .layer(WHITE, HALF_VERTICAL_MIRROR)
                        .layer(BLACK, STRIPE_CENTER)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, RHOMBUS_MIDDLE)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(WHITE, STRIPE_LEFT)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(BLACK, STRIPE_RIGHT)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_LEFT)
                        .layer(WHITE, HALF_HORIZONTAL_MIRROR)
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(BLACK, STRIPE_RIGHT)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, RHOMBUS_MIDDLE)
                        .layer(BLACK, STRIPE_DOWNRIGHT)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_RIGHT)
                        .layer(WHITE, HALF_HORIZONTAL)
                        .layer(BLACK, STRIPE_LEFT)
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, SQUARE_BOTTOM_LEFT)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_TOP)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, RHOMBUS_MIDDLE)
                        .layer(BLACK, STRIPE_DOWNRIGHT)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_LEFT)
                        .layer(WHITE, HALF_HORIZONTAL_MIRROR)
                        .layer(BLACK, STRIPE_RIGHT)
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_RIGHT)
                        .layer(BLACK, STRIPE_LEFT)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(BLACK, STRIPE_CENTER)
                        .layer(WHITE, BORDER)
                        .layer(WHITE, STRIPE_TOP)
                        .layer(WHITE, STRIPE_BOTTOM)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_MIDDLE)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, CROSS)
                        .layer(WHITE, STRIPE_TOP)
                        .layer(WHITE, STRIPE_BOTTOM)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, SQUARE_TOP_LEFT)
                        .layer(BLACK, SQUARE_BOTTOM_RIGHT)
                        .layer(WHITE, STRIPE_CENTER)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, BORDER)
                    )
                    .banner(BLACK, builder -> builder // 
                        .layer(WHITE, STRIPE_TOP)
                        .layer(WHITE, STRIPE_BOTTOM)
                        .layer(WHITE, STRIPE_MIDDLE)
                        .layer(WHITE, BORDER)
                    )
                    .banner(BLACK, builder -> builder // 
                        .layer(WHITE, STRIPE_TOP)
                        .layer(WHITE, STRIPE_BOTTOM)
                        .layer(WHITE, STRIPE_MIDDLE)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, TRIANGLES_BOTTOM)
                        .layer(WHITE, TRIANGLES_TOP)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_TOP)
                        .layer(WHITE, RHOMBUS_MIDDLE)
                        .layer(WHITE, CURLY_BORDER)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_DOWNRIGHT)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, HALF_VERTICAL_MIRROR)
                        .layer(BLACK, STRIPE_TOP)
                        .layer(BLACK, STRIPE_BOTTOM)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_DOWNRIGHT)
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(WHITE, DIAGONAL_LEFT)
                        .layer(WHITE, DIAGONAL_LEFT_MIRROR)
                        .layer(WHITE, BORDER)
                    )
                    .banner(WHITE, builder -> builder // 
                        .layer(BLACK, STRIPE_DOWNLEFT)
                        .layer(BLACK, STRIPE_DOWNRIGHT)
                        .layer(WHITE, DIAGONAL_RIGHT_MIRROR)
                        .layer(WHITE, DIAGONAL_RIGHT)
                        .layer(WHITE, BORDER)
                    )
                    .build();
}
